Repository ls1mardyn/ls1-mardyn, pull requests merged in 2019-10, with the labels that each got.

#93 initial rebalancing phase for general domain decomposition
  examples/Argon/200K_18mol_l/config_autopas_allOptions.xml
  src/parallel/GeneralDomainDecomposition.cpp
  src/parallel/GeneralDomainDecomposition.h
Labels: AutoPas, enhancement

#94 Fix minimal domain check for GDD
  src/Simulation.cpp
  src/parallel/ALLLoadBalancer.h
  src/parallel/GeneralDomainDecomposition.cpp
  src/parallel/GeneralDomainDecomposition.h
  src/parallel/LoadBalancer.h
Labels: AutoPas, bug

#107 Fix neighbor acquirer (GDD, push-pull)
  Jenkinsfile
  examples/Argon/200K_18mol_l/config.xml
  src/parallel/CommunicationPartner.h
  src/parallel/GeneralDomainDecomposition.cpp
  src/parallel/NeighborAcquirer.cpp
  src/parallel/NeighborAcquirer.h
  src/parallel/NeighbourCommunicationScheme.cpp
  src/parallel/tests/NeighborAcquirerTest.cpp
  src/parallel/tests/NeighborAcquirerTest.h
Labels: bug

#102 ODF cell processor
  doc/Plugins_Summary.dox
  src/io/ODF.cpp
  src/io/ODF.h
  src/particleContainer/adapter/ODFCellProcessor.cpp
  src/particleContainer/adapter/ODFCellProcessor.h
Labels: enhancement
