Repository ls1mardyn/ls1-mardyn, pull requests merged in 2024-12, with the labels that each got.

#353 Remove executable mode from source and input files
  examples/Adsorption-plugin-version/CO2/CO2_LJ93Wall.xdr
  examples/Adsorption-plugin-version/CO2/CO2_LJ93Wall_snapshot.png
  examples/Adsorption-plugin-version/CO2/components_co2_stoll.xml
  examples/Adsorption-plugin-version/CO2/run01/config.xml
  examples/Adsorption-plugin-version/CO2/sphereparams_co2_stoll.xml
  examples/DropletCoalescence/components.xml
  examples/DropletCoalescence/liq/config_2_replicateLiq.xml
  examples/DropletCoalescence/mixing_2c.xml
  examples/DropletCoalescence/vap/config_4_replicateVap.xml
  examples/DropletCoalescence/vle/config_5_droplet.xml
  examples/comparison.xml
  examples/general-plugins/WallPotential_Mirror.xml
  src/io/Mkesfera.cpp
  src/io/Mkesfera.h
  src/io/ReplicaGenerator.cpp
  src/io/ReplicaGenerator.h
  src/plugins/COMaligner.cpp
  src/plugins/COMaligner.h
  src/plugins/PluginBase.h
  src/plugins/PluginFactory.h
  src/plugins/TestPlugin.h
  src/plugins/WallPotential.cpp
  src/plugins/WallPotential.h
  src/plugins/tests/COMalignerTest.cpp
  src/plugins/tests/COMalignerTest.h
  src/plugins/tests/DensityControlTest.cpp
  src/plugins/tests/DensityControlTest.h
  src/plugins/tests/VelocityExchangeTest.cpp
  src/plugins/tests/VelocityExchangeTest.h
  src/plugins/tests/compressionTest.cpp
  src/plugins/tests/compressionTest.h
  src/utils/Random.cpp
  test_input/1clj-regular-2x2x2-offset.inp
  test_input/2clj-regular.inp
  test_input/ForceCalculationTestF0.inp
  test_input/ForceCalculationTestU0.inp
  tools/grideval/Makefile
Labels: clean-up

#357 Remove unused compression code
  CMakeLists.txt
  cmake/modules/compression.cmake
  cmake/modules/lz4.cmake
  doc/compression.dox
  src/CMakeLists.txt
  src/plugins/compression.cpp
  src/plugins/compression.h
  src/plugins/tests/compressionTest.cpp
  src/plugins/tests/compressionTest.h
Labels: clean-up

#355 Fix option parser's long option handling
  src/utils/OptionParser.cpp
Labels: bug

#360 Fix CI for Ubuntu 24.04
  .github/workflows/ls1_test.yml
  README.md
  cmake/modules/autopas.cmake
Labels: CI

#361 Fix/plugin EnergyRAPL
  src/plugins/EnergyRAPL.cpp
  src/plugins/EnergyRAPL.h
Labels: bug, WindHPC

#300 Fix quaternion default initialisation
  src/molecules/AutoPasSimpleMolecule.cpp
  src/molecules/AutoPasSimpleMolecule.h
  src/molecules/FullMolecule.cpp
  src/molecules/FullMolecule.h
  src/molecules/MoleculeRMM.h
  src/molecules/Quaternion.h
Labels: bug
