Repository ls1mardyn/ls1-mardyn, pull requests merged in 2024-06, with the labels that each got.

#322 Fix bug in static code analysis and add exit codes
  checks/run-staticAnalysis.sh
  src/ensemble/ChemicalPotential.h
  src/ensemble/EnsembleBase.h
  src/ensemble/GrandCanonicalEnsemble.h
  src/ensemble/PressureGradient.h
  src/io/Adios2Reader.h
  src/io/Adios2Writer.h
  src/io/TimerProfiler.h
  src/io/tests/Adios2IOTest.h
  src/parallel/ALLLoadBalancer.h
  src/parallel/CommunicationBuffer.h
  src/parallel/ForceHelper.h
  src/parallel/StaticIrregDomainDecomposition.cpp
  src/parallel/StaticIrregDomainDecomposition.h
  src/plugins/COMaligner.h
  src/plugins/DirectedPM.h
  src/plugins/Dropaligner.h
  src/plugins/EnergyRAPL.h
  src/plugins/LoadImbalanceThroughSleepPlugin.h
  src/plugins/PluginBase.h
  src/plugins/PluginFactory.h
  src/plugins/TestPlugin.h
  src/plugins/WallPotential.h
  src/plugins/profiles/DOFProfile.h
  src/plugins/profiles/DensityProfile.h
  src/plugins/profiles/KineticProfile.h
  src/plugins/profiles/ProfileBase.h
  src/plugins/profiles/TemperatureProfile.h
  src/plugins/profiles/Velocity3dProfile.h
  src/plugins/profiles/VelocityAbsProfile.h
  src/plugins/tests/COMalignerTest.h
  src/plugins/tests/compressionTest.h
  src/utils/FixedSizeQueue.h
  src/utils/FunctionWrapper.h
  src/utils/nnls.h
Labels: bug, CI

#311 Fix xml parser attribute parsing
  src/utils/xmlfile.cpp
  src/utils/xmlfileUnits.cpp
Labels: bug

#326 Improvements of MaxCheck plugin
  src/plugins/MaxCheck.cpp
  src/plugins/MaxCheck.h
Labels: enhancement
